### ISSUE TITLE
List of Cards

### ISSUE THREAD

**Issue by badabam** [badabam/lean-coffee-board-hh-web-21-3#1]
# Value proposition (user story)

*As a* student
*I want to* have a list of the most frequent questions
*I order to* know that I did not miss anything important.

# Description (text, scribble, wireframe, design)
![homescreen](https://user-images.githubusercontent.com/157286/120199050-1791b100-c223-11eb-8527-72046bde6038.png)

## Text:
- delivered by Jerry

# Acceptance criteria

- [ ] Sorted alphabetically ascending

# Complexity (low, medium, high)
low

# Tasks
- [x] Create feature branch
- [x] Build card component (storybook)
- [x] Write tests for card component
- [ ] Add cards to App
- [x] Add global styles
