### ISSUE TITLE
Card with Author

### ISSUE THREAD

**Issue by badabam** [badabam/lean-coffee-board-hh-web-21-3#5]
## Value statement - a requirement, not a solution
As a **user**
I need **to know the card's author's name**
so that **I know with whom to discuss the card**

## Description (Text, Scribble, Wireframe, Design)
![story-with-author](https://user-images.githubusercontent.com/157286/120466452-619fa180-c39f-11eb-92d9-79f0d8f1c726.png)

## Acceptance criteria
- [ ] Author should be right-aligned
- [ ] Author should be "dotted out", if too long (John Verylongnamethatdoesnot...) to fit in one row

## Tasks
- [ ] feature branch
- [ ] update component test
- [ ] add example for normal and long author in storybook
- [ ] update component

## Complexity
low
