### ISSUE TITLE
Form for new cards

### ISSUE THREAD

**Issue by badabam** [badabam/lean-coffee-board-hh-web-21-3#6]
## Value statement - a requirement, not a solution
As **a user**
I need to **create new cards**
so that **we can have different topics in our discussions**

## Description (Text, Scribble, Wireframe, Design)
![create-card](https://user-images.githubusercontent.com/157286/120469342-80ebfe00-c3a2-11eb-8a38-2bd9571f309d.png)
![create-card-button](https://user-images.githubusercontent.com/157286/120467535-9102de00-c3a0-11eb-8bbc-73442dc45848.png)

## Acceptance criteria
- [ ] Save data to localstorage
- [ ] Back button brings you back to startpage and empties the form
- [ ] Create button adds a new card to startpage at the top
- [ ] Create button empties the form and sets focus to text input
- [ ] Button is disabled until both inputs are filled (with anything but whitespace characters)
- [ ] Add card button (startpage) is fixed at the bottom of the screen (and not pushed down by cards)
- [ ] The url does not change

## Tasks
- [ ] Feature branch
- [ ] Button component w/ storybook and tests
- [ ] Form component w/ storybook and test
- [ ] Update App with components and logic
- [ ] Add localStorage

## Complexity
medium
