### ISSUE TITLE
Remember author

### ISSUE THREAD

**Issue by badabam** [badabam/lean-coffee-board-hh-web-21-3#7]
## Value statement - a requirement, not a solution
As a **user**
I need **to have my name saved**
so that **I don't have to write it correctly for each card**

## Description (Text, Scribble, Wireframe, Design)
- First time, form is as before
- After first card, see wireframe

![edit-author](https://user-images.githubusercontent.com/157286/120479009-bf3aea80-c3ad-11eb-8038-3a560a3e7617.png)

## Acceptance criteria
- [ ] Author is saved in browser
- [ ] Click on "edit" shows form with two inputs and "author" prefilled and the value is selected
- [ ] Click on "edit" does not delete card text (input above author)
- [ ] Click on "back" keeps the last saved author

## Tasks
- [ ] Feature branch
- [ ] Update form component (with new storybook stories and tests)
- [ ] Add logic
- [ ] Use localStorage

## Complexity
medium
